### ISSUE TITLE
Consider updating to Ubuntu 18.04

### ISSUE THREAD

**Issue by ItalyPaleAle** [Azure/LAMP#5]
(Low priority)

Updating to Ubuntu 18.04 would allow us to use PHP 7.2

Ubuntu 16.04 only supports PHP 7.0 in the official repos, which has reached EOL for the PHP team. It's supported from the Ubuntu team, but some apps will likely start deprecating PHP 7.0 support soon.

**Comment by UmakanthOS** [comment]
Ubuntu 18.04.5 LTS has been supported for a while now.
